### ISSUE TITLE
Can't find this package in Package control

### ISSUE THREAD

**Issue by TejasAvinashShetty** [SublimeLinter/SublimeLinter-flake8#107]
SublimeLinter-flake8 can't be found when trying to install it from package control.
>Sublime Text version 3.1.1 
> Mac OS 10.13.6
<img width="1440" alt="screen shot 2019-02-22 at 7 31 24 pm" src="https://user-images.githubusercontent.com/27445854/53247189-be985180-36d8-11e9-8185-cc4234509fd3.png">

**Comment by kaste** [comment]
Make sure you don't have it already. Try 'Enable Package'.

**Comment by talune** [comment]
I'm also unable to locate SublimeLinter-flake8 in package control.
I've confirmed that it is not already installed.

**Comment by braver** [comment]
must've been a fluke
