### ISSUE TITLE
SublimeLinter-flake8 doesn't support extra flake8 extensions

### ISSUE THREAD

**Issue by CVirus** [SublimeLinter/SublimeLinter-flake8#11]
I installed flake8 via pip + the following extensions:

`cvirus@leon:~$ flake8 --version
2.2.5 (pep8: 1.5.7, import-order: 0.5.1, pep257: 0.2.1, mccabe: 0.2.1, pyflakes: 0.8.1, naming: 0.2.2) CPython 2.7.6 on Linux`

Unfortunately, SublimeLinter-flake8 will only highlight the errors for pyflakes, pep8, and mccabe .. While the rest of the extensions have no effect, except for the "import-order" extension where its errors are only shown in SublimeText console but are not highlighted in the editor:

`SublimeLinter: flake8: models.py ['/usr/bin/python', '/usr/local/bin/flake8', '--config=setup.cfg', '--jobs=1', '-'] 
SublimeLinter: flake8 output:
stdin:2:1: I100 Imports statements are in the wrong order. from django.conf should be before from django.db`

If I run flake8 from the command line, I get the following:

`cvirus@leon:~/projects/fer2etak$ flake8 fer2etak/nada/models.py
fer2etak/nada/models.py:1:1: D100  Docstring missing
fer2etak/nada/models.py:2:1: I100 Imports statements are in the wrong order. from django.conf should be before from django.db
fer2etak/nada/models.py:6:1: D101  Docstring missing
fer2etak/nada/models.py:10:1: D102  Docstring missing
fer2etak/nada/models.py:14:1: D203  Expected 1 blank line *before* class docstring, found 0
fer2etak/nada/models.py:14:1: D204  Expected 1 blank line *after* class docstring, found 0
fer2etak/nada/models.py:14:1: D400  First line should end with '.', not 'g'
fer2etak/nada/models.py:29:1: D102  Docstring missing
fer2etak/nada/models.py:33:1: D101  Docstring missing
fer2etak/nada/models.py:38:1: D102  Docstring missing`

Non of the above errors are highlighted in the editor.

Is this a bug or I'm missing something ?

**Comment by grotewold** [comment]
Fixed by #21
