### ISSUE TITLE
can get E,W type errors, but no F type errors

### ISSUE THREAD

**Issue by rainnnnny** [SublimeLinter/SublimeLinter-flake8#110]
does it mean pyflakes is not working?

sublimetext pkg is installed and flake8 is installed system globally 
![image](https://user-images.githubusercontent.com/15228876/60419941-13188400-9c19-11e9-890f-9fb0669d1e11.png)
![image](https://user-images.githubusercontent.com/15228876/60420075-68549580-9c19-11e9-9c81-6a00e93a4f01.png)

**Comment by kaste** [comment]
Which version of flake8 you're using here? It should print all installed plugins if you do a `flake8 -h` as the last output. E.g. on my computer

```
...
Installed plugins: flake8-docstrings: 1.3.0, pydocstyle: 3.0.0, flake8-pyi:
19.3.0, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1
```

You can also check what you have installed using `pip list`.

**Comment by rainnnnny** [comment]
thanks for reply! 

![image](https://user-images.githubusercontent.com/15228876/60502414-5691f180-9cf0-11e9-970b-b3720e5e850c.png)
It's like this

**Comment by kaste** [comment]
Well, that's what I have. Can you make a python file with a `F` error, and lint it on the command line. Then open the file in Sublime. You can turn on `debug` mode in the SublimeLinter settings as well which will print verbose logging to Sublime's console (`View > Show Console`).

**Comment by rainnnnny** [comment]
strange.. I directly tried writing a test file in sublime, and it worked(above), but it does'nt work in my project file(below)
![image](https://user-images.githubusercontent.com/15228876/60566729-59492100-9d9a-11e9-86d6-dfb0e5a559f1.png)
![image](https://user-images.githubusercontent.com/15228876/60566817-a3ca9d80-9d9a-11e9-89e6-0def0ab2de39.png)

and console printed these when i change the project file to trigger lint
![image](https://user-images.githubusercontent.com/15228876/60566990-39fec380-9d9b-11e9-95c2-cd8c500f7af4.png)

**Comment by kaste** [comment]
You can see that file has a syntax error:

![image](https://user-images.githubusercontent.com/8558/60587793-9f4fb600-9d95-11e9-942e-4b68e894a119.png)

Often flake8 and other linters bail out on syntax errors and can't show other errors then.

Tip: If you see in the status bar that flake8 reported an error `ctrl+k, a` will show all errors in a panel, likewise `ctrl+k, n` will jump to the next error.

**Comment by rainnnnny** [comment]
Thanks so much... I'm sorry I barely used linter before so I didn't know the syntax error will cause bail-out... it's ok now

And thanks for the tip :)

**Comment by kaste** [comment]
👌
