### ISSUE TITLE
Error: 'selector' is mandatory in 'cls.defaults'

### ISSUE THREAD

**Issue by EmilStenstrom** [SublimeLinter/SublimeLinter-flake8#112]
It seems linting with flake8 has stopped working for me. If I open up the console i see this error message:

```
flake8: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
flake8: Defining 'cls.version_args' has no effect. Please cleanup and remove these settings.
flake8: Defining 'cls.version_re' has no effect. Please cleanup and remove these settings.
flake8: Defining 'cls.version_requirement' has no effect. Please cleanup and remove these settings.
flake8: Defining 'cls.inline_settings' has no effect. Please cleanup and remove these settings.
flake8: Defining 'cls.inline_overrides' has no effect. Please cleanup and remove these settings.
flake8: Do not implement 'build_cmd'. SublimeLinter will change here in the near future.
flake8 disabled. 'selector' is mandatory in 'cls.defaults'.
 See http://www.sublimelinter.com/en/stable/linter_settings.html#selector
```

I'm using Sublime Text 3.2.1

**Comment by EmilStenstrom** [comment]
Here's a relevant change from sass-lint: https://github.com/skovhus/SublimeLinter-contrib-sass-lint/pull/32/files

**Comment by kaste** [comment]
You're not on the latest version. Maybe you use a git checkout?

**Comment by EmilStenstrom** [comment]
Hi, thanks for the quick reply (and for you maintaining this excellent library overall too!).

I were not on a git checkout, but I think you where right anyways. I removed the package using Package Control (removed 4.2.3) and installed it again, and now I'm getting a separate error (pyenv instead of virtualenv). I'll work in that one.

Thanks again!
