### ISSUE TITLE
Extend "E501 line too long" match till end of line

### ISSUE THREAD

**Issue by iamkroot** [SublimeLinter/SublimeLinter-flake8#119]
Currently, positions of lints with `E501` are handled by the `PythonLinter` base class. Since flake8 gives the column (like 80) as the hint, the base class extends the lint to the end of scope. This sometimes gives confusing results, like only outlining a single character (which would suggest that something is wrong with that char, rather than the line):
![Screenshot_20210710_112257](https://user-images.githubusercontent.com/29517049/125153423-3021af00-e171-11eb-8dbe-57708796181d.png)

This doesn't match the semantics of E501 - everything after that column is a part of the warning/error, so the outline should extend till the end of the line. Here's the expected result:
![Screenshot_20210710_112657](https://user-images.githubusercontent.com/29517049/125153505-c3f37b00-e171-11eb-962c-b1c9166578b5.png)

**Comment by kaste** [comment]
Totally reasonable.  Do you want to try a PR?
