### ISSUE TITLE
no flake8 version

### ISSUE THREAD

**Issue by mrvkino** [SublimeLinter/SublimeLinter-flake8#12]
I have the flake8 linter installed and working, but when I load the package I get these messages:

```
SublimeLinter: debug mode: off 
SublimeLinter: WARNING: import of flake8.engine module in flake8 failed, linter will not work with python 3 code 
Writing file /Users/Shadow/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings with encoding UTF-8 (atomic)
reloading Packages/User/SublimeLinter.sublime-settings
found 35 files for base name Main.sublime-menu
Package Control: Skipping automatic upgrade, last run at 2014-11-18 10:23:54, next run at 2014-11-18 11:23:54 or after
Registering handler with address ('localhost', 53801)
SublimeLinter: WARNING: no flake8 version could be extracted from:
  File "/Users/Shadow/.pyenv/shims/flake8", line 3
    [ -n "$PYENV_DEBUG" ] && set -x
                      ^
SyntaxError: invalid syntax
```

When running the command `flake8 --verions` I get the following results `2.2.5 (pep8: 1.5.7, pyflakes: 0.8.1, mccabe: 0.2.1) CPython 2.7.8 on Darwin`

**Comment by playpauseandstop** [comment]
Strange, but I still has same issue,

```
SublimeLinter: WARNING: import of flake8.engine module in flake8 failed, linter will not work with python 3 code
SublimeLinter: WARNING: no flake8 version could be extracted from:
  File "/Users/playpauseandstop/.pyenv/shims/flake8", line 3
    [ -n "$PYENV_DEBUG" ] && set -x
                      ^
SyntaxError: invalid syntax
```

when using:

* SublimeLinter3 v3.4.39
* SublimeLinter-flake8 v1.2.14

on Sublime Text 3 Build 3083 at Mac OS X 10.10.3. Any ideas how to fix it?

**Comment by bear** [comment]
I can confirm this is still happening with SublimeLinter3 and -flake8

After some debugging I found that it's because the patch is calling out to pyenv but using /bin/sh instead of the login shell, which for me is bash.

I changed the run_shell_cmd call to be:

out = run_shell_cmd((env['SHELL'], '-l', '-c', 'echo ""; %s which %s' % (pyenv, script))).strip().decode().split('\n')[-1]

and it's now working. the 'echo "";' part is to push the colour code escapes from my prompt onto their own line so they could be stripped, unsure if that is always required but it couldn't hurt

**Comment by yanokwa** [comment]
Just to build on what @bear did...

The file:line in question is 
`~/Library/Application\ Support/Sublime\ Text\ 3/Packages/SublimeLinter/lint/util.py:945`

env didn't work for me, so I used os.environ

    # out = run_shell_cmd((pyenv, 'which', script)).strip().decode()
    out = run_shell_cmd((os.environ['SHELL'], '-l', '-c', 'echo ""; %s which %s' % (pyenv, script))).strip().decode().split('\n')[-1]

@groteworld I'm happy to submit a patch if you are happy with this fix.

**Comment by groteworld** [comment]
Feel free to pass it up and I'll test it out. It's pretty nasty looking but i'm not sure there is a better way. I encourage the use of `.format()` instead of `%` for the string concatenation.
