### ISSUE TITLE
SublimeText 4 Support

### ISSUE THREAD

**Issue by meyt** [SublimeLinter/SublimeLinter-flake8#123]
I've installed this package through `git clone` and its working on SublimeText v4126.
But the package marked as only ST3 on PackageControl which prevents to install by PackageControl.

**Comment by kaste** [comment]
That must have been a fluke; at least I can see it:

![image](https://user-images.githubusercontent.com/8558/148622587-25b93c9a-065a-4760-9e87-2b4debcfb580.png)

**Comment by meyt** [comment]
@kaste I've checked again with clear ST setup and you're right its there. Thanks
