### ISSUE TITLE
setup.cfg flake8 settings ignored when using module instead of executable

### ISSUE THREAD

**Issue by lrowe** [SublimeLinter/SublimeLinter-flake8#13]
My project wide flake8 settings are defined in a setup.cfg:

```
[flake8]
max-line-length = 100
```

This worked fine when I was using python2 flake8 (presumably as the executable was used), but now I've switched to a python3 flake8 these settings are being ignored:

```
SublimeLinter: flake8: __init__.py <builtin> 
SublimeLinter: flake8 options: {'max_complexity': -1, 'reporter': <class 'SublimeLinter-flake8.linter.Flake8.get_report.<locals>.Report'>, 'jobs': '1'} 
SublimeLinter: flake8 output:
__init__.py:106:80: E501 line too long (99 > 79 characters)
__init__.py:129:80: E501 line too long (99 > 79 characters)
__init__.py:164:80: E501 line too long (82 > 79 characters)
__init__.py:165:80: E501 line too long (84 > 79 characters)
__init__.py:198:80: E501 line too long (99 > 79 characters)
```

I prefer using setup.cfg for settings as they will also apply for flake8 runs from the command line or travis.

**Comment by groteworld** [comment]
Is this still the case, sorry this fell through the cracks, try flake8 3.0.0 and feel free to open if it's still a problem
