### ISSUE TITLE
List unpack operator in assignment triggers false positive

### ISSUE THREAD

**Issue by jnluy** [SublimeLinter/SublimeLinter-flake8#130]
See attached
![image](https://github.com/SublimeLinter/SublimeLinter-flake8/assets/50705586/9ec195f1-738f-4d0c-8274-2d519adfa182)

**Comment by kaste** [comment]
Oh, what version of python does support that?   Anyway, that's an flake8 error, we just display it.  Did you check that flake8 does support that, for example running the latest on the command line?

**Comment by jnluy** [comment]
Sorry, I will open an issue with flake8.
