### ISSUE TITLE
Show error code in popup box

### ISSUE THREAD

**Issue by jmagnusson** [SublimeLinter/SublimeLinter-flake8#14]
Would make it much easier to know which codes to ignore. An example of the popup menu I'm talking about:
![screen shot 2015-01-26 at 17 04 35](https://cloud.githubusercontent.com/assets/190835/5902752/6f876d2e-a57d-11e4-96d3-656e77e68ca2.png)

I think https://github.com/dreadatour/Flake8Lint has this built in.

**Comment by FichteFoll** [comment]
:+1:

The old SL did this and it made finding the correct code to ignore a lot easier. It's also easier to find similar errors or warnings in the panel when you can just search for it by typing.

This should happen in both the popup and the statusbar text.

**Comment by grotewold** [comment]
This has been merged in, sorry it took so long!
