### ISSUE TITLE
Highlighting wrong occurrences of unused import

### ISSUE THREAD

**Issue by simonluijk** [SublimeLinter/SublimeLinter-flake8#15]
I am not sure if this is a bug with sublimelinter-flake8 or flake8

![2015-02-11-121156_3840x1080_scrot](https://cloud.githubusercontent.com/assets/63589/6145950/a2686902-b1e7-11e4-9b70-f9b2c971b38b.png)

**Comment by skj3gg** [comment]
Sounds extremely similar to SublimeLinter/SublimeLinter3#188 about SL-pyflakes (probably using an extremely similar regex). I'm currently looking if this can be refined more within SL3

**Comment by simonluijk** [comment]
Yes, I think that is the same issue.

**Comment by FichteFoll** [comment]
Also same as #8.

**Comment by groteworld** [comment]
duplicate of https://github.com/SublimeLinter/SublimeLinter3/issues/188
