### ISSUE TITLE
flake8: noqa option disables all checks for the whole file

### ISSUE THREAD

**Issue by MrTango** [SublimeLinter/SublimeLinter-flake8#20]
This line should be ignored in checks, but this disable all checks for the whole file, which is wrong.
import pdb;pdb.set_trace()  # flake8: noqa

**Comment by playpauseandstop** [comment]
To disable one line you should use,

```python
import pdb; pdb.set_trace()  # noqa
```

syntax. 

When flake8 sees `flake8: noqa` comment it disables all checks for whole file, this is [proper behavior](http://flake8.readthedocs.org/en/2.4.0/)

**Comment by MrTango** [comment]
i know, but if i do that, the check for the whole document is disabled and that is not what i want and i know from syntaxtic in vim ;)

**Comment by MrTango** [comment]
Ah you mean only # noqa, but this does nothing i get still the E702 then, only # flake8: noqa, works but disables the complete check of the document which is wrong.

**Comment by playpauseandstop** [comment]
Yeah, that other side of `pep8` as not every error ignored by `# noqa` comment.

See more in my request for ignoring `E731` error by `# noqa`, https://github.com/jcrocholl/pep8/issues/379

**Comment by sigmavirus24** [comment]
flake8 3.0.0b2 (which will soon be finalized as 3.0.0) will allow you to do `# noqa: E702,E731`.
