### ISSUE TITLE
ignore "line too long"

### ISSUE THREAD

**Issue by fnkr** [SublimeLinter/SublimeLinter-flake8#23]
I want to ignore "line too long" messages but for some reason it doenst work.
This is from my `SublimeLinter.sublime-settings`:
```json
"flake8": {
    "@disable": false,
    "args": [],
    "builtins": "",
    "excludes": [],
    "ignore": "E501",
    "jobs": "1",
    "max-complexity": -1,
    "max-line-length": null,
    "select": ""
},
```

The error code `E501` is correct (I think) - if I enable debug mode and open the console:
```
script.py:26:80: E501 line too long (97 > 79 characters)
```

**Comment by fnkr** [comment]
I also tried setting `max-line-length` to some higher value but it seems like this is ignored too.

**Comment by fnkr** [comment]
For some reason it does work now, after I restarted Sublime Text a few times and changed some completely independent options (e.g. gutter theme) - I cant explain what happend.

**Comment by wdscxsj** [comment]
I bumped into the same issue today with SublimeLinter 4.0.2, and this seems to work fine:

```
"flake8": {
    "args": ["--ignore", "E501"]
}
```

**Comment by kaste** [comment]
There is only so much you can do. I'll take documentation PR's as well. 😄

**Comment by amurabito** [comment]
it's worth noting that this did solution does not work on the latest sublime and packages, and the solution is now this: 

// SublimeLinter Settings - User
{
    "lint_mode": "load_save",
    "linters": {
        "flake8": {
            "args": ["--ignore=E501,E127,E128,W191"],
        }
    }
}

as detailed in the thread here: 

https://github.com/SublimeLinter/SublimeLinter/issues/1050

**Comment by sambarluc** [comment]
On: Sublime Text 3.1.1 Build 3176
       Sublime Linter 4.6.4
       Sublime Linter-flake8 4.1.0

This is still an issue, and using the "args" syntax does not cure it.

**Comment by braver** [comment]
@sambarluc the args setting works so there must be something else going on in your setup/configuration. You need to tell us a lot more about what you're trying to do and what doesn't work. Perhaps this page helps: http://www.sublimelinter.com/en/stable/troubleshooting.html

**Comment by sambarluc** [comment]
From the command line, everything works fine. `flake8` returns the right errors according to the options I set on the command line.

In st3, on the status bar, I correctly get the summary of the output from flake8.

Setting the debug mode to true, I see that the command used for flake8 is

```
    SublimeLinter: #1 linter.py:1174: Running ...

      <my_workdirectory>  (working dir)
      cat <file.py> | /usr/bin/flake8 --format default -
```

which does miss the files I had set in `args`, and the errors I get in st3 reflect this.

**Comment by braver** [comment]
What do your settings look like?

**Comment by braver** [comment]
@kaste perhaps some help here? I tried setting `"args:": "--ignore=E303 --max-line-length=100"` but that doesn't do anything for me either.

**Comment by kaste** [comment]
Well, it's args not args:

**Comment by braver** [comment]
Hot damn, sometimes you just need a second pair of eyes. Or schema validation. Thanks!

**Comment by sambarluc** [comment]
Good good, that was silly!
Thanks, you don't imagine how I stared at it... but shouldn't an error be raised somewhere?

**Comment by braver** [comment]
@sambarluc we have a validation mechanism for most settings, but linter plugins can define any additional setting they want. So, for all SublimeLinter knows "args:" is a valid setting for SL-flake8. I can imagine mechanisms that would catch such errors, but the trade off would be a hit in flexibility and probably quite a few lines of code.

**Comment by diazgilberto** [comment]
It is interesting that `flake8 file.py --ignore=E501` ran in the terminal does work but not as a setting in...

```
// SublimeLinter Settings - User
{
    "paths": {
        "linux": [],
        "osx": [
            "/usr/local/bin/cspell",
        ],
        "windows": [],
    },
    "statusbar.counters_template": "(w:{} | e:{})",
    "show_panel_on_save": "view",
    "linters": {
      "flake8": {
        "args": ["--ignore=E501"]
      }
    }

}
```
I'm getting an error still...

![screen shot 2019-01-20 at 3 34 18 pm](https://user-images.githubusercontent.com/9165819/51445271-e0ad4700-1cc8-11e9-8f3d-b4fd4e04b8f8.png)

**Comment by braver** [comment]
> ["--ignore=E501"]

@diazgilberto  What if you make that a string, not an array?

**Comment by diazgilberto** [comment]
<img width="719" alt="screen shot 2019-01-21 at 7 34 27 am" src="https://user-images.githubusercontent.com/9165819/51477812-32001980-1d4f-11e9-98bd-82da8f5f9e01.png">

![screen shot 2019-01-21 at 7 35 17 am](https://user-images.githubusercontent.com/9165819/51477821-36c4cd80-1d4f-11e9-8289-b97e80c2a58b.png)

**Comment by braver** [comment]
Are you running pep8 alongside flake?

**Comment by kaste** [comment]
🤔 	I don't recognize the status bar text.

**Comment by christopherpickering** [comment]
This also seems to work -
```json
// SublimeLinter Settings - User
{
    "linters": {
      "flake8": {
            "args": ["--max-line-length=99"],
        }
    }
}

```

**Comment by rokejulianlockhart** [comment]
How do I use ignore=E501 (or whichever version of it is current) in Flake8 via VSCode?

![image](https://user-images.githubusercontent.com/42837531/212444741-58cf1ef4-5028-4d0d-8d10-1d144c0ce952.png)

**Comment by braver** [comment]
This is the repo for SublimeLinter, for Sublime Text, not VS Code.

**Comment by rokejulianlockhart** [comment]
Sorry @braver. The extension states that this is the repository to report bugs to, so since I found a perfect bug, I thought that it would be relevant. Any idea of where to ask such a question?

I at least expected the syntax to be identical for both problems.
