### ISSUE TITLE
~/.config/flake8 config file not working

### ISSUE THREAD

**Issue by jmfederico** [SublimeLinter/SublimeLinter-flake8#24]
Hello!

Flake8 usually reads configuration options from ~/.config/flake8 but when used with SublimeLinter-flake8 it seems as if the file wasn't been loaded.

Is that expected? How can I get it to read the file?

Thanks

**Comment by jeffrand** [comment]
+1

**Comment by ptim** [comment]
:+1:  I'd like this to work on a per project level, like .eslintrc, etc

**Comment by jmagnusson** [comment]
Not all projects use the same flake8 settings so this would be a good addition to the project.

**Comment by syslo** [comment]
+1

**Comment by fjsj** [comment]
+1

**Comment by rattrayalex** [comment]
+1

**Comment by JonathanHolvey** [comment]
Weirdly, some settings in a per-directory config file do work. For example, the `ignore` setting in the following config will indeed suppress the selected errors, but other settings don't get picked up (or are overridden).

    [Flake8]
    ignore = E123, E124
    exclude = test.py
    max-line-length = 100

**Comment by jannschu** [comment]
In my case I had the anaconda package installed, which uses its own linter. So I configured anaconda with
```
{
	"anaconda_linting": false
}
```
and now it is working.

**Comment by groteworld** [comment]
with recent changes you should be able to use a `.flake8` file in the project.
