### ISSUE TITLE
[Help/question] How to persist gutter or outlines?

### ISSUE THREAD

**Issue by JokerQyou** [SublimeLinter/SublimeLinter-flake8#25]
After a linting is done, the gutters and outlines are shown. But once I start typing again, all of them are gone, and I have to save to lint again. What I want is: when I start typing, only the gutter / outline of that specific line disappear, and others remain unchanged. If this cannot be achieved, then I want all the gutters / outlines to remain the same when I start typing. 
Is that possible? Thanks

**Comment by lcb** [comment]
Well you can achieve this - kind of - by running linting in "background" mode. However there is a slight lag and it eats tons of CPU.

Also it  might not be as easy as it sounds. e.g. if you insert or remove a line the annotatins get into the wrong place (so maybe line changes should trigger a clear?).

Still I give
+1
in the hope somebody smart out there has a good idea how to make linting more real-time.

**Comment by groteworld** [comment]
This is sadly way too big for flake8 to do. As lcb said, the best we can really do is the background mode.
