### ISSUE TITLE
No highlight on unused imports

### ISSUE THREAD

**Issue by JokerQyou** [SublimeLinter/SublimeLinter-flake8#30]
I know there are some opened issues about wrong highlight on unused imports, but I think this one is different.
If I have the import clause separated on multiple line, there will be a gutter showing a warning sign. But there will be no keyword highlighted, thus you cannot use `Ctrl + K, n` to jump to that warning.

The screenshot is as followed:
![image](https://cloud.githubusercontent.com/assets/1465267/11266716/791855a8-8ee1-11e5-8915-df113644eaea.png)

**Comment by groteworld** [comment]
Sorry it took so long to look over this one. Could you provide the output from flake8 cli on this kind of issue? it will help in determining where the fault is, though i have suspicion it IS related to https://github.com/SublimeLinter/SublimeLinter3/issues/188

**Comment by JokerQyou** [comment]
It seems to have been fixed somehow, I think. Now for multi-line imports, the warning sign will show up on the first line, and all warnings about `unused import` will be shown if I move cursor to that line.
