### ISSUE TITLE
Misleading info about @python setting

### ISSUE THREAD

**Issue by M4urice** [SublimeLinter/SublimeLinter-flake8#32]
The README.md reads:

> @python    A meta setting that indicates the python version of your source files. Use this inline or at the global level, not within the linter’s settings.

Why should I not use it within the linter's settings (works fine for me BTW)? And how would I set it at global level instead?

**Comment by ptim** [comment]
I'm searching for answers here, too... tried several things, will report back if I have any joy :/

**Comment by ptim** [comment]
ugh, scratch that, note to self: just RTFM!

I've just started on projects with python3, and had not installed flake8 with pip3

thumbs down :)

```
# For python 3.x
[sudo] pip-3.x install flake8
```

**Comment by groteworld** [comment]
The `@python` setting should be working again, please let me know if this is still an issue.
