### ISSUE TITLE
Adding custom flake8 args in Python3

### ISSUE THREAD

**Issue by ianlawson1234** [SublimeLinter/SublimeLinter-flake8#36]
Hey!

I've just bumped up to Python3 and have found that I can no longer pass extra args to flake8 via the SublimeLinter plugin.

I'm currently defining args in my SublimeLinter prefs as so:

```
"args": [
    "--radon-max-cc",
    "6"
]
```

Looking at the logs in debug mode - Python2 shows something like this:

`SublimeLinter: flake8: list_.py ['/python2.7/bin/python', '/python2.7/bin/flake8', '--radon-max-cc', '1', '--max-complexity=-1', '--jobs=1', '--max-line-length=100', '--ignore=P101,P102,P103', '-']`

However, in Python3, it looks to be operating in a totally different manner:

```
SublimeLinter: flake8: list_.py <builtin> 
SublimeLinter: flake8 options: {'max_line_length': 100, 'jobs': '1', 'reporter': <class 'SublimeLinter-flake8-master.linter.Flake8.get_report.<locals>.Report'>, 'max_complexity': -1, 'ignore': ['P101', 'P102', 'P103']}

```
I'm struggling to see how I should be passing through the custom arguments!

Any help would be much appreciated.

Cheers,
Ian

**Comment by kaste** [comment]
Fixed by #38
