### ISSUE TITLE
Can't disable E501

### ISSUE THREAD

**Issue by NetGeekFR** [SublimeLinter/SublimeLinter-flake8#39]
Hi, and thanks for reading.

So, I just upgraded to Sublime Text 3 and installed SublimeLinter via Package Control.

I just noticed that now, SublimeLinter takes into account E501, but that disturbs me and I would like to disable it (disable the warning).

I installed pip, pep8 and SublimeLinter-pep8 too

Here's my SublimeLinter.sublime-settings : 

{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {},
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}

What should I add to disable E501 ? I tried everything I could find on the Web...

PS : Sorry for my bad english

**Comment by kaste** [comment]
You're on the `SublimeLinter-flake8` repo not `pep8`

**Comment by NetGeekFR** [comment]
Oh, sorry
