### ISSUE TITLE
Plugin tries to run flake8 in python2 instead of python3

### ISSUE THREAD

**Issue by spookey** [SublimeLinter/SublimeLinter-flake8#40]
I was a happy SublimeLinter-flake8 user, once..

Some days ago it stopped working (don't know when exactly), fiddling around I discovered that the plugin tries to launch ``flake8`` inside ``python2`` instead of ``python3``.

If I start up Sublime (with Sublimelinter ``"debug": true``) I have the following output in the console:

    startup, version: 3114 osx x64 channel: stable
    executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
    working dir: /
    packages path: /Users/spky/Library/Application Support/Sublime Text 3/Packages
    state path: /Users/spky/Library/Application Support/Sublime Text 3/Local
    zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
    zip path: /Users/spky/Library/Application Support/Sublime Text 3/Installed Packages
    ignored_packages: ["CSS", "Vintage"]
    pre session restore time: 0.421869
    loading dictionary Packages/Language - English/en_US.dic
    startup time: 0.641907
    first paint time: 0.65541
    reloading plugin Default.auto_indent_tag
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.convert_syntax
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_context_url
    reloading plugin Default.open_file_settings
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.profile
    reloading plugin Default.quick_panel
    reloading plugin Default.run_syntax_tests
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.show_scope_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin Rust.plugin
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.02-bz2
    reloading plugin CSS3.css3_completions
    reloading plugin CSS3.rgb_to_hex
    reloading plugin CSS3.validator
    reloading plugin EditorConfig.EditorConfig
    reloading plugin GitGutter.git_gutter
    reloading plugin GitGutter.git_gutter_change
    reloading plugin GitGutter.git_gutter_compare
    reloading plugin GitGutter.git_gutter_events
    reloading plugin GitGutter.git_gutter_handler
    reloading plugin GitGutter.git_helper
    reloading plugin GitGutter.view_collection
    reloading plugin Package Control.1_reloader
    reloading plugin Package Control.2_bootstrap
    reloading plugin Package Control.Package Control
    reloading plugin SublimeLinter-contrib-rustc.linter
    SublimeLinter: rust linter loaded 
    reloading plugin SublimeLinter-flake8.linter
    SublimeLinter: flake8 linter loaded 
    reloading plugin SublimeLinter-jsl.linter
    SublimeLinter: jsl linter loaded 
    reloading plugin SublimeLinter-json.linter
    SublimeLinter: json linter loaded 
    reloading plugin SublimeLinter-luacheck.linter
    SublimeLinter: luacheck linter loaded 
    reloading plugin SublimeLinter-shellcheck.linter
    SublimeLinter: shellcheck linter loaded 
    reloading plugin SublimeLinter.commands
    reloading plugin SublimeLinter.sublimelinter
    plugins loaded
    SublimeLinter: debug mode: on 
    SublimeLinter: temp directory: /var/folders/46/ly858_nd3f19frcj_zghlnlc0000gn/T/SublimeLinter3-spky 
    SublimeLinter: find_python(version='3', script=None, module=None) 
    SublimeLinter: find_python: requested version = {'major': 3, 'minor': None} 
    SublimeLinter: user shell: /usr/local/bin/zsh 
    SublimeLinter: computed PATH using /usr/local/bin/zsh:
    /usr/local/bin
    /usr/local/sbin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /opt/X11/bin
    /Users/spky/bin
    /usr/local/MacGPG2/bin
    /Library/TeX/texbin
     
    SublimeLinter: find_posix_python: python3 => /usr/local/bin/python3 
    SublimeLinter: find_python: system python = /usr/local/bin/python3 
    SublimeLinter: find_python: available version = {'major': 3, 'minor': 5} 
    SublimeLinter: find_python: <= ('/usr/local/bin/python3', None, 3, 5) 
    SublimeLinter: sys.path for /usr/local/bin/python3:
    /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python35.zip
    /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5
    /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin
    /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload
    /usr/local/lib/python3.5/site-packages
     
    SublimeLinter: json activated: <builtin> 
    Package Control: Skipping automatic upgrade, last run at 2016-06-14 19:00:45, next run at 2016-06-14 20:00:45 or after

Yay, looks great, the ``SHELL`` is discovered correctly, as well as all system ``PATH``s..

The moment when I type into some Python file, the console outputs this:

    SublimeLinter: find_python(version=None, script='flake8', module=None) 
    SublimeLinter: find_python: default python = /usr/local/bin/python 
    SublimeLinter: find_python: available version = {'major': 2, 'minor': 7} 
    SublimeLinter: find_python: 'flake8' path = /usr/local/bin/flake8 
    SublimeLinter: find_python: <= ('/usr/local/bin/python', '/usr/local/bin/flake8', 2, 7) 
    SublimeLinter: flake8 version query: /usr/local/bin/python /usr/local/bin/flake8 --version 
    SublimeLinter: WARNING: no flake8 version could be extracted from:
    Traceback (most recent call last):
      File "/usr/local/bin/flake8", line 7, in <module>
        from flake8.main import main
    ImportError: No module named flake8.main
 
I have ``flake8`` installed (via ``pip3 install -U flake8``), it also works correctly (if called manually from the commandline).

Steps I've already tried:
* Putting an ``"@python": 3.5`` metavar inside the SublimeLinter config, tried any level
  * no success
* Reinstall ``SublimeLinter-flake8``
  * no success
* Reinstall ``flake8`` (as well as ``pep8``, ``pyflakes`` & ``mccabe``)
  * no success
* Reinstall ``SublimeLinter``
  * no success
* Complete reinstall of ``Sublime``, importing my old settings afterwards.
  * no success! surprise!

What am I missing, what am I doing wrong?
Please help me become a happy user of SublimeLinter-flake8 again.

**Comment by kaste** [comment]
Try the hotfix I described in #38

**Comment by spookey** [comment]
Hey,
I just extracted the Package using ``PackageResourceViewer`` and patched the ``linter.py`` like [you suggested](https://github.com/SublimeLinter/SublimeLinter-flake8/pull/38#issuecomment-225540273).
It works now.

Please merge #38 as soon as possible 😄 
Thanks for the hint.

**Comment by spookey** [comment]
Just a little follow-up to #41

I just installed the latest version from PackageControl (and removed my patched version first) - it works again.
Now I'm a happy user again 😸 

Thank you all!

**Comment by nfvs** [comment]
Not to resurrect an old thread, but #41 is the wrong fix for this.

SublimeLinter tries to use your system's python version, which in your case seems to be 2. If you want to use flake8 with a version that's not your system default, you need to either set the version to 3 in the global settings, or do that that in per-project basis with a `.sublimelinterrc` file, like this very project does:

https://github.com/SublimeLinter/SublimeLinter-flake8/blob/master/.sublimelinterrc#L2

PR #41 will lock flake8 to ST's internal python version, which is 3, for *everyone*, and will ignore the version defined in the settings.

This means you can no longer choose a different version, and even worse, you cannot define a virtual environment binary (virtualenv which can contain libraries that your system does not, but are required to avoid "module not found" errors).
