### ISSUE TITLE
Version conflict with flake8-3.0.0b1

### ISSUE THREAD

**Issue by brianbruggeman** [SublimeLinter/SublimeLinter-flake8#42]
Versions..

OS:  OS X 10.10.5
Sublime Text: v3 build 3114
Sublimelinter Plugin: 3.7.4
Sublimelinter-flake8 Plugin: 2.0.1
system flake8: 3.0.0b1

Work-around: I dropped back to flake8 v2.4.1 and seems to be working just fine.

**Comment by sigmavirus24** [comment]
What was the conflict?

**Comment by brianbruggeman** [comment]
I'm not sure;  I had no visuals and no errors thrown in my debug window.

**Comment by groteworld** [comment]
Was this ever resolved? I'm not sure what would have changed this between versions, but maybe it was a pathing issue. I'm closing due to age and a full rewrite of plugin but please let me know if this is still occurring.

**Comment by brianbruggeman** [comment]
Sorry for not getting back.  I think it has been resolved.
