### ISSUE TITLE
Missing docstring in public module

### ISSUE THREAD

**Issue by ArjunHariharan** [SublimeLinter/SublimeLinter-flake8#50]
SubmlimeLinter-flake8 throws an error "missing docstring in public module" on all the files. I don't see this error when i run flake8 on the terminal.

`flake8 --version
3.2.1 (pyflakes: 1.3.0, flake8-docstrings: 1.0.2, pydocstyle: 1.1.1, mccabe: 0.5.2, pycodestyle: 2.2.0) CPython 2.7.9 on Darwin`

`pep8 --version
1.5.7
`

**Comment by milieu** [comment]
+1

**Comment by ianfitzpatrick** [comment]
+1 I have this problem too.

**Comment by Tagirijus** [comment]
+1 I also have this problem.

**Comment by groteworld** [comment]
This was most likely caused SL-flake8 using the wrong flake8, a new version of SL-flake8 has been released and if configured to the correct version of python you're running should clean up this. Feel free to open if this is not the case.
