### ISSUE TITLE
linter ignores flake8 plugins

### ISSUE THREAD

**Issue by driesdesmet** [SublimeLinter/SublimeLinter-flake8#52]
I get a different output from running the flake8 command on the terminal compared to what sublimelinter tells me. For example:
```bash
$ flake8 public
public/admin.py:3:6: H304  No relative imports. 'from .models import PublicPicture' is a relative import
```

I've tried to specifically include 'H' errors in the settings, but it still doesn't show up:
```javascript
"settings":
    {
        "anaconda_linting": false,
        "SublimeLinter": {
            "debug": true,
            "linters": {
                "flake8": {
                    "@disable": false,
                    "args": [],
                    "builtins": "",
                    "excludes": [],
                    "ignore": "",
                    "select": "H304"
                }
            },
            "paths": {
                "linux": [],
                "osx": [
                    "/Users/dries/src/csm/_csm/bin"
                ],
                "windows": []
            },
            "python_paths": {
                "linux": [],
                "osx": [
                    "/Users/dries/src/csm/_csm/bin"
                ],
                "windows": []
            },
        },
        "python_interpreter": "/Users/dries/src/csm/_csm/bin/python"
    }
```
Is this plugin not expected to show warnings/errors displayed by flake8 plugins?

The plugins I'm using for flake8 are these:

```bash
$ flake8 --version
2.5.5 (pep8: 1.5.7, mccabe: 0.2.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1, pyflakes: 0.8.1) CPython 2.7.12 on Darwin
```

The specific plugin that warns about relative imports is 'hacking.core'. Or is there maybe a better way to enforce this coding style: http://docs.openstack.org/developer/hacking/

**Comment by jannschu** [comment]
Had the same problem. Used flake8 form virtualenv. Added setting
```
"linters":
{
	"flake8": {
		"executable": "${project}/.venv/bin/flake8"
	}
}
```

to solve the issue.

**Comment by groteworld** [comment]
I would make sure that the flake8 SL's running is the same as the flake8 you are running. jannaschu's answer should fix this or there has been a new release of SL-flake8 that fixes much of those pathing errors. Feel free to open if you are still experiencing plugins not appearing. in ST when they are in the CLI
