### ISSUE TITLE
SublimeLinter-flake8 not finding paths

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter-flake8#54]
First of all thank you for SublimeLinter and thank you for extending it with Flake8, as it makes coding Python in Sublime so much more enjoyable!

I believe I have a problem with my paths settings of SublimeLinter-flake8.
This expresses itself in:
- Python 3.6 syntax (e.g. "f-strings") marked as erroneous
- imports from a module folder I have included in the PythonPath also being marked

Both sublime-anaconda and python itself do not express any problem with the respective python files.
(Anaconda understands the Python 3.6 syntax and autocompletes with content from the extra folder. Python itself can execute the scripts without any error.)

Tell me what information you require to understand this problem and I will provide it.
Thanks.

Below are two links to threads on Sublime Forum and stackoverflow respectively where I discuss this issue.

They also contain an excerpt from my sublime-linter's .sublime-setttings file.

[Sublime Forum](https://forum.sublimetext.com/t/sublimelinter-pyflakes-not-finding-module-in-extended-path/29687)

[stackoverflow](https://stackoverflow.com/questions/45118632/sublimelinter-pyflakes-not-finding-module-in-extended-path)

**Comment by groteworld** [comment]
this was most likely due to SL-flake8 finding a 2.7 flake8 or running in the ST 3.3 binary. I would check now that this is not an issue, or that you can configure SL-flake8 with the `@python` config.

I'm going to close with the release of SL-flake8 v3.0.0, feel free to open if it's still not working
