### ISSUE TITLE
Add setting to deactivate the inline error message popups.

### ISSUE THREAD

**Issue by brocoli** [SublimeLinter/SublimeLinter-flake8#55]
Ever since a recent-ish update to SublimeLinter-flake8, there's an intrusive inline popup that shows up while I am typing. It's especially bad because it overrides SublimeText's auto-complete box. I can't find a way to deactivate it.

SublimeLinter already has an option to lint on save and to show a popup when a lint happens. Why is this functionality replicated in SublimeLinter-flake8?

**Comment by groteworld** [comment]
To disable the inline popup, check the SublimeLinter User setting `"tooltips": false` and make sure it's set to `false`. If they are still appearing, let me know!

**Comment by brocoli** [comment]
wow... I'm sorry, I can't believe I missed that setting ^^v

Since I've only had tooltips appear for flake8 errors, I assumed they were a SublimeLinter-flake8 thing when I couldn't find a way to turn them off. Thank you, everything is working fine now!
