### ISSUE TITLE
Automatically ignore some whitespace errors

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter-flake8#65]
For good reasons, settings like `max-line-length` and `max-complexity` should be not held within sublime settings, but in `.flake8` or another config file. 

The exception here should be the typical whitespace warnings Sublime will autocorrect for us on save. These are:

W291 | trailing whitespace
-- | --

W293 | blank line contains whitespace
-- | --

W391 | blank line at end of file
-- | --

**Comment by braver** [comment]
@kaste how do you feel about things like the inline settings? I've got an issue open for it at https://github.com/SublimeLinter/SublimeLinter3/issues/679 and I really really want to "won't fix" it. Especially for the python based linters which already have various ways to configure them. Do you think we can deprecate them in an elegant manner? I kinda can't imagine a lot of people use these settings, but I've been wrong about such things before.

**Comment by kaste** [comment]
Oh shit, these features can be disabled. Maybe we can copy-paste some code from say `Prettier` or so.

**Comment by braver** [comment]
To integrate "fixer" features you mean?

**Comment by kaste** [comment]
Yes, on the subject of this issue. Naively you would just add these 3 error codes. Are there more?

**Comment by braver** [comment]
Well, I'm not 100% sure about the python ecosystem, but in JS/TS land there are lots of ways to run a fixer over the code. Ideally you want a setup where you suppress those errors in your editor if they're going to be fixed automatically anyway. With e.g. tslint the fixer is part of the linter and leans on the same configuration. That's kind of a good reason to suppress them in SL. What codes you're going to want to suppress is situational though. I think we already have a pretty good method of doing that via args.

**Comment by kaste** [comment]
This is not completely trivial. flake8 does not support including or excluding errors from the command line. From http://flake8.pycqa.org/en/latest/user/invocation.html we have 

> --append-config=APPEND_CONFIG
                        Provide extra config files to parse in addition to the
                        files found by Flake8 by default. These files are the
                        last ones read and so they take the highest precedence
                        when multiple files provide the same option.

So we need to write such a config.file, and append it by default unless the user opts-out or so. Added label: help wanted.

**Comment by cixtor** [comment]
> flake8 does not support including or excluding errors from the command line

Maybe I am missing something here, but it seems that `--ignore=errors` solves this.

```
--ignore=errors
  Comma-separated list of errors and warnings to ignore
  (or skip). For example, ``--ignore=E4,E51,W234``.
  (Default: E121,E123,E126,E226,E24,E704)
```

**Comment by kaste** [comment]
`--ignore` overrules a flake8 conf file. What I mean is *include* e.g. something like `--add-ignore`
