### ISSUE TITLE
util.py is unloaded and reloaded at startup

### ISSUE THREAD

**Issue by gerardroche** [SublimeLinter/SublimeLinter-flake8#70]
When ST "reloads" plugins at startup if a plugin is already loaded it will unload it then reload it. `linter.py` imports `util.py` so it gets loaded, when ST then tries to load util.py it sees that it's already loaded so it unloads it and then reloads. This is extra overhead and can cause side-effect hard-to-debug issues. 

ST only autoloads modules in the root package so the fix is to move util.py into a sub directory or move the code into `linter.py`.

I don't know when I'd get a chance to submit a PR or which fix you'd prefer. Looking at the code in util I'd just push the code into `linter.py`, it's not a huge amount of code.

**Comment by kaste** [comment]
Nope. 😉

This is a showcase implementation and will get merged back into SublimeLinter core. You can actually find a PR over there.

**Comment by gerardroche** [comment]
Are all the linters being moved to the core?

**Comment by kaste** [comment]
No, of course not.

Current implementation here introduced a new base python linter and its util.py. Both are PRed to go into core. 

This was merely a deploy strategy, so we could test if the new linter is good enough.

**Comment by gerardroche** [comment]
I was confused about this until it was merged upstream and now it all makes sense. Good work! :+1:
