### ISSUE TITLE
shebang of source is ignored

### ISSUE THREAD

**Issue by bizoo** [SublimeLinter/SublimeLinter-flake8#72]
Cannot configure the last version (for sublimelinter 3) to work with shebang.

I'm on Windows and before (with my [PR](https://github.com/SublimeLinter/SublimeLinter/pull/407)):
When my script start with `#!python3`, flake8 from python3 is used.
When no shebang or start with `#!python2`, flake8 from python2 is used.

It seems to me that shebang is now totally ignored, probably because the `@pyhon` was removed from `cmd = ('flake8@python', '*', '-')`

**Comment by kaste** [comment]
Hi @bizoo. 

Yes, you're right `shebang` is currently not implemented. (That has nothing to do with `@python` being dropped from `cmd`. It is just that the method `shebang_match` is not implemented anymore.) 

See: https://github.com/SublimeLinter/SublimeLinter/blob/a4dee7de12e4f497c7df49ccf8803dfb1f3a8afd/lint/python_linter.py#L52

And then: 

https://github.com/SublimeLinter/SublimeLinter/blob/a4dee7de12e4f497c7df49ccf8803dfb1f3a8afd/lint/python_linter.py#L68-L79

Can you try to copy-paste here a bit and see if we can get it working again. 

Please note though, that *shebang* has been dropped in the new SL4 which is already beta.

**Comment by bizoo** [comment]
Hi @kaste, thanks for your quick reply.

Well if shebang is not supported in SL4 anymore, I think we can close this issue.
No need to spend time on an almost obsolete code.

But I don't get the reason shebang was dropped from SL4.
I often work on projects containing both python2 and python3 code, and having the correct flake version used automatically was a big plus.

Is there a way in SL4 to switch python interpreter without changing settings ?

Anyway, I (very) slowly switch my main editor to VSCode, this will motivate me to do it quicker (in fact VSCode doesn't support shebang either, but you can switch the python interpreter with 2 click).

Thanks again.
