### ISSUE TITLE
Wrong word highlighted on F401

### ISSUE THREAD

**Issue by meshy** [SublimeLinter/SublimeLinter-flake8#8]
![screenshot from 2014-06-27 16 39 48](https://cloud.githubusercontent.com/assets/767671/3414008/4f30dac4-fe11-11e3-8fef-2587d53f45b6.png)

![screenshot from 2014-06-27 16 40 15](https://cloud.githubusercontent.com/assets/767671/3414016/5cc74646-fe11-11e3-98b7-cacb9b36c15c.png)

![screenshot from 2014-06-27 16 40 31](https://cloud.githubusercontent.com/assets/767671/3414023/658b6186-fe11-11e3-97d0-408c1b623ed4.png)

Note that the first instance of "static" is highlighted, but it is the second instance that is the issue.

**Comment by groteworld** [comment]
This seems to be a bigger issue of SL so moving to https://github.com/SublimeLinter/SublimeLinter3/issues/188
