### ISSUE TITLE
flake8 config options don't get recognized in SublimeLinter v4.0.0-rc.9.9.9

### ISSUE THREAD

**Issue by OdinTech3** [SublimeLinter/SublimeLinter-flake8#83]
In the v4 of Sublime Linter, flake8's linter settings found in SublimeLinter.sublime-settings doesn't get recognized when linting my python files. so for example if i have this set of settings in  the SublimeLinter.sublime-settings file for my flake8 linter

```
"linters":
    {
        "flake8":
        {
           "args": [],
            "excludes": [],
            "ignore": "E731",
            "max-complexity": 7,
            "max-line-length": 120,
            "select": ""
        },
},
```

The linter wont recognized it or respect it when i am in a python file, however if I configure it like so 

```
"linters":
    {
        "flake8":
        {
            "disable": false,
            "args": [
                "--max-complexity","7",
                "--max-line-length", "120",
                "--ignore", "E731"],
            "excludes": [],
            "select": ""
        },
},
```

It works and the linter respects the configuration that I have set in the args field of flake8's linter settings. Is this the new behaviour of this plugin or is it a bug?

**Comment by kaste** [comment]
Yeah, @braver removed that yesterday.

**Comment by braver** [comment]
👋

**Comment by OdinTech3** [comment]
Alright, is there a changelog one can be keeping tabs on for all the changes occuring to the plugin?

**Comment by braver** [comment]
Not right now for the pre-releases, we'll do a "what's new" when we're ready to launch v4.
