### ISSUE TITLE
Read flake8 configuration from setup.cfg file

### ISSUE THREAD

**Issue by boompig** [SublimeLinter/SublimeLinter-flake8#88]
When invoked from the command-line, flake8 will read setup.cfg for options. I notice that the flake8 SublimeLinter plugin does not do this.

**Comment by kaste** [comment]
SublimeLinter itself uses `setup.cfg` https://github.com/SublimeLinter/SublimeLinter/blob/master/setup.cfg

So there must be something else going on. Enable debug mode for SublimeLinter, check the working dir `cwd`. Check your flake8 settings either globally or per project.

**Comment by braver** [comment]
@boompig if you still have issues with, check where your setup.cfg hangs out and perhaps change the [working_dir](http://www.sublimelinter.com/en/stable/linter_settings.html#working-dir) setting.

**Comment by STRML** [comment]
For anyone picking this up in 2021:

If you want to pick up in-directory config like `.flake8` or `setup.cfg`, your `working_dir` for flake8 should be `$file_path`, not `${folder:$file_path}`, as this defaults to `$folder` first when in project mode, which is the project root.

```json
  "linters": {
    "flake8": {
      "working_dir": "$file_path"
    }
  }
```
