### ISSUE TITLE
WARNING: cannot locate 'flake8'

### ISSUE THREAD

**Issue by vgoklani** [SublimeLinter/SublimeLinter-flake8#98]
Hello - I periodically get this error: "WARNING: cannot locate 'flake8".

I'm using anaconda, where/how should I add this information? Which configuration file should this be placed in?

Thank you! 👍

**Comment by braver** [comment]
@vgoklani please re-open with some more [debug info](http://www.sublimelinter.com/en/stable/troubleshooting.html) if you want to debug this further.
